### PR TITLE
fix Makefile to build docker plugin

### LINKED ISSUE #43: Docker Module not Built - Cannot Use without Kube
The Makefile does not have a build path for building the docker.so module for this container.

Therefor use of attempted use of `CRUNCHY_WATCH_PLATFORM=docker` results in a Seg Fault.

```
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | plugin.Open(/opt/cpm/bin/crunchy-watch/plugins/docker.so): realpath failed
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | panic: runtime error: invalid memory address or nil pointer dereference
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1571ebe]
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    |
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | goroutine 1 [running]:
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | main.loadPlatformModule(0x7ffc0778ae27, 0x6, 0xc4200dbe08, 0x1)
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | 	/home/dwagneradm/buildenv/cdev/src/github.com/crunchydata/crunchy-watch/util.go:42 +0x1de
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | main.main()
pgwatch_pgwatcher.1.25qgkikv4am8@stldopsdock02    | 	/home/dwagneradm/buildenv/cdev/src/github.com/crunchydata/crunchy-watch/main.go:229 +0x316
```

### PR DESCRIPTION
**Pull request by davecramer**
bring docker example run.sh up to date

fixes #43

### CODE REVIEW

**Comment by Illydth** [comment]
@davecramer I assume this only brings the run.sh up to date to actually execute a docker plugin.  As I don't see any code being put into docker.so in this PR, I assume that using "watch" without Kube or OpenShift is still a non-starter correct?

It's been a couple weeks since I was deep into this and at this point am unsure what I did with the existing code set I was working with to initially produce the problem reported in #43 so I'm trying to figure out if this PR actually fixes the issue that PGWatch used with docker SegFaults when run or if this PR actually does make watch functional in a normal docker/non kube environment?

Looking at the changes it doesn't look like it...

**Comment by abrightwell** [comment]
@Illydth - you are correct. Until the docker plugin is implemented this project only supports failover in a kube/openshift environment. I've created issue #49 in the hopes that it will be completed in a future version. To avoid any obvious confusion, we should temporarily remove any references to docker until it is minimally supported.

**Comment by davecramer** [comment]
We are of course encouraging Pull Requests!

**Comment by jmccormick2001** [comment]
thanks, I think at this point I'll close this PR out since it doesn't really do much towards a Docker implementation, if someone wants to do a PR with the implementation I'll be happy to review.

**Pull request closed without merging**
