### PR TITLE
use godep

### PR DESCRIPTION
**Pull request by davecramer**
Switch to using godep instead of glide

### CODE REVIEW

**Comment by abrightwell** [comment]
This would be a step backwards. If anything migrating to the official go tool, 'dep' would be the better choice. https://github.com/golang/dep

**Comment by davecramer** [comment]
from the same site:

dep is the official experiment, but not yet the official tool. Check out the Roadmap for more on what this means!

**Comment by abrightwell** [comment]
Godep is still a step backwards from glide. 'dep' is the official tool and is 'production safe'. It will eventually be packaged with go. Glide is also compatible with 'dep'. Go projects are moving away from 'godep' not towards it. Please do not make this change.

**Comment by davecramer** [comment]
fair enough.

**Pull request closed without merging**
